### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by snipdesign** [johannesc/induction-hob#3]
Hi Johannes,

I'm an industrial design engineer from The Netherlands and would like to contact you about your induction hob project...

Will you send me an email with one or more ways to contact you? Please email me at bassnippert@gmail.com? Thanks!

Bas

**Comment by shmrymbd** [comment]
hi @johannesc good work. lucky we found your shared info. we stuck at 8n1.. thanks anyway. great job!
